# Generated by Django 3.2 on 2022-04-05 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=150, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['office'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Serviço')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ManyToManyField(to='core.Office', verbose_name='Cargo')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['users'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Desconto')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('date_attendance', models.DateField(auto_now_add=True, verbose_name='Data do Atendimento')),
                ('date_service', models.DateField(verbose_name='Data da Limpeza')),
                ('status_attendance', models.CharField(choices=[('PE', 'Pendente'), ('RE', 'Realizado'), ('CA', 'Cancelado')], max_length=50, verbose_name='Status do Atendimento')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('client_phone', models.CharField(max_length=14, verbose_name='Telefone do Cliente')),
                ('client_address', models.CharField(max_length=250, verbose_name='Endereço do Cliente')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.services', verbose_name='Serviço Contratado')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['services'],
            },
        ),
    ]
